# Generated by Django 4.1.5 on 2023-06-08 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_user_followed_follows_user_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='user_follower',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
